# name: Deploy Auth Service
# 
# on:
#   push:
#     branches:
#       - main
#       - master
#     paths:
#       - "AuthService.Presentation/**"
#       - "AuthService.Application/**"
#       - "AuthService.Domain/**"
#       - "Authservice.Infrastructure/**"
#       - ".github/workflows/deploy-auth.yml"
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
# 
#       - name: Install Railway
#         run: npm i -g @railway/cli
# 
#       - name: Deploy
#         run: railway up --service auth-service --detach
#         env:
#           RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
